# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "elmnst-global-terraform-state-bucket"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "live/global/./terraform.tfstate"
    region         = "ap-southeast-1"
  }
}
