# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region                   = "ap-southeast-1"
  shared_credentials_files = ["~/.aws/credentials"]
  profile                  = "devops-admin"
}
